### ISSUE TITLE
Run Adobe/Discord app

### ISSUE THREAD

**Issue by ghost** [smokes/adobe-rpc#37]
I keep getting the 'error' Run Adobe/Discord app while adobe illustrator and discord are open.
It's just not detecting it.
![Schermafbeelding 2021-02-05 165233](https://user-images.githubusercontent.com/71753983/107056380-94130680-67d2-11eb-86ba-7a06cb9c8262.png)

**Comment by pcislocked** [comment]
Disable Hyper-V.

**Comment by pcislocked** [comment]
I have no idea why hyper-v interferes with it but I enabled it, adober-rpc got broken. I disabled it, it works again. I checked the code, it returns a problem while checking PID 72 (Secure System), which is something related to hyper-v afaik.

Also disable stuff like windows sandbox and virtualization platform until secure system process is gone

**Comment by pcislocked** [comment]
Upon further investigation, I found out that it is actually fixed at a pull request, but the code owner didn't merge it. Although my problem was due to the Hyper-V, it has nothing to do with your problem. I don't know if it is allowed to say it here, but I merged almost all of the PRs at my own repo this evening.

**Comment by ghost** [comment]
I thank you.
I tried your repo and that worked.

I need virtualization and for Hyper-V, idk but something needs it and I don't know what.

But again, thank you for your repo
